clean: true
copyright: "Copyright © 2019 Yahoo Japan Corporation. All Rights Reserved."
output: docs
module: YJLoginSDK
xcodebuild_arguments: [-workspace, YJLoginSDK.xcworkspace, -scheme, YJLoginSDK]
