name: Doc-PR

on:
  pull_request:
    branches:
      - master

jobs:
  generate-document:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v1

    - name: install-jazzy
      run: gem install jazzy

    - name: Generate document
      run: jazzy
