name: Doc

on:
  push:
    branches:    
      - master

jobs:
  generate-document:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v1

    - name: install-jazzy
      run: gem install jazzy

    - name: Generate document
      run: jazzy

    - name: Commit files
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          Generate jazzy document
          skip-checks: true
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout master
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
